# Generated by Django 3.1.5 on 2021-01-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='insta.jpg', upload_to='profile_pics'),
        ),
    ]
